### ISSUE TITLE
Bring whole code from https://github.com/Pragament/flutter_upi_credit_debit_log

### ISSUE THREAD

**Issue by ndubbaka** [Pragament/flutter_upi_credit_debit_log_app#2]
Currently https://github.com/Pragament/flutter_upi_credit_debit_log doesn't use any state management.
Refactor using riverpod state management and push new refactored code to https://github.com/Pragament/flutter_upi_credit_debit_log_app

https://github.com/Pragament/flutter_upi_credit_debit_log_app uses https://github.com/wednesday-solutions/flutter_template with script manager https://pub.dev/packages/derry
 ## Quick build steps
```
dart pub global activate derry
flutter pub get
derry generate all
derry launch dev
```
Don't clone. Fork default branch into your own GitHub account. Develop in your fork project. After development is completed, submit a PR to this project.

view the screenshots in readme file at https://github.com/Pragament/flutter_upi_credit_debit_log/blob/master/README.md

- Use hive database, go_router & riverpod for state management
- Android, iOS - Light & dark modes
- App languages(English, Telugu, Hindi)
- Documentation https://dart.dev/effective-dart/documentation Comment full code wherever needed for documentation - https://dart.dev/language/comments

```yaml
Pubspec.yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: null
  go_router: null
  hive_flutter: null
  intl: null
  riverpod_annotation: null
```
